
= Foundations

First off - link:https://github.com/HubPress/hubpress.io[Hubpages.io] rocks, no?

Hivewing.io is here to help with all the nittly grittly bits of deploying processes on devices and managing them remotely.

We are a platform you build your product on top of.  Similar to AWS or Heroku, and even some similarity to AWS Elastic Beanstalk.  We can update binaries remotely, let you reverse tunnel things (like ssh), even do configuration and data collection. And since we're a platform, if you only want some of the awesomeness - feel free to pick and choose what best suits your needs.

== Some Definitions
One can't get too far down the road without laying a foundation.  As we have heard, it's better to build upon a solid rock, than on shifting sand. So let us solidify what we're talking about, ok?

=== Worker Process
It all starts here. Hivewing is built upon processes. Good ol' basic processes like you would run from the command line.  We could have tried to abstract things a bit more - and had you run some javascript in our container, or maybe had you write some http server code.  But we like the foundation of managing processes.  When you write code to have it run on your distributed devices, the process is where it starts.  Hivewing is really an infrastructure to run (and keep running) processes on distributed hosts.  It adds on a lot of other helpful tools, but that is the core mission.

So - here is a Process.  (your process to be precise)
++++
<div class='mermaid'>
graph TD;
    WorkerProcess
</div>
++++


== Worker Process Manager
Someone needs to manage all these processes.  Starting them up and making sure they stay up.  Additionally, when you have a new version of a process that needs to get deployed, the worker process manager will gracefully shutdown  the processes, and spin up the new processes.  

++++
<div class='mermaid process-manager'>
	graph TB;
    subgraph ProcessManager
      WorkerProcess1
      WorkerProcess2
      WorkerProcessN
    end
</div>
++++

== Worker Device
Each device that you build and deploy runs a single worker process manager.  It is termed a Worker Device. Or usually we just call it a Worker for short.  The worker is the unit which hivewing manages in most cases.

++++
<div class='mermaid worker-device'>
	graph TB;
    subgraph Worker1
      subgraph ProcessManager
        WorkerProcess1
        WorkerProcess2
        WorkerProcessN
      end
    end
    subgraph Worker2
      subgraph ProcessManager
        WorkerProcess1
        WorkerProcess2
        WorkerProcessN
      end
    end
</div>
++++




